### ISSUE TITLE
Still maintained ?

### ISSUE THREAD

**Issue by superboum** [cozy-labs/emails#5]
If I'm right, this is a standalone email app extracted from cozy-cloud.
But, even if cozy/cozy-emails seems really active, things seems to be a bit different for this repository.
Can we expect some updates ? Or it's just a testing repo, not really maintained ?

A self hosted guy who really love your interface and cozy-labs/emails simplicity

**Comment by frankrousseau** [comment]
Yes we plan to update the standalone version with the Cozy version. We'll release it in July.

**Comment by superboum** [comment]
Thanks !
